name: pre-commit
description: Runs pre-commit hooks

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pre-commit
      run: sudo apt-get install pre-commit
      shell: bash

    - name: Disable R.cache integration
      run: echo "options(R.cache.enabled = FALSE)" > $HOME/.Rprofile
      shell: bash

    - name: Set other cache paths
      run: |
        echo "XDG_CACHE_HOME=$RUNNER_TEMP" >> $GITHUB_ENV
        echo "TMPDIR=$RUNNER_TEMP" >> $GITHUB_ENV
      shell: bash

    - name: Cache pre-commit environment
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.XDG_CACHE_HOME }}/pre-commit
          ${{ env.XDG_CACHE_HOME }}/R
          ${{ env.XDG_CACHE_HOME }}/pip
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
