name: pre-commit
description: Runs pre-commit hooks

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pre-commit
      run: sudo apt-get install pre-commit
      shell: bash

    - name: Cache pre-commit environment
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('/.pre-commit-config.yaml') }}

    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
