name: pre-commit
description: Runs pre-commit hooks

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Create Python venv
      run: uv venv
      shell: bash

    - name: Install pre-commit
      run: uv pip install pre-commit
      shell: bash

    - name: Cache pre-commit environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
          ~/.cache/R
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      run: >
        uv run pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
