name: pre-commit
description: Runs pre-commit hooks

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

      # R is no longer preinstalled on GitHub runners as of Ubuntu 24.04, so we
      # need to install it to support consumers that are checking R code
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.4"
        use-public-rspm: true

    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash

    - name: Cache pre-commit environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
          ~/.cache/R
          ~/.local/share/renv/cache
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
