name: 'pre-commit'
description: 'Runs pre-commit hooks'
inputs:
  python-version:
    description: 'The Python version to use'
    required: true
    default: '3.10.12'
  hooks:
    description: 'The hooks to run, separated by commas'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pre-commit
      run: sudo apt-get install pre-commit
      shell: bash

    - name: Cache pre-commit environment
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Configure pre-commit hooks
      run: python ${{ github.action_path }}/pre-commit/parse_hook_string.py "${{ inputs.hooks }}"
      shell: bash

    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
