name: pre-commit
description: Runs pre-commit hooks

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        # No cache since we only need one dependency and we don't want to rely
        # on the existence of lockfiles for cache hashing
        enable-cache: false
        prune-cache: false

    - name: Install pre-commit
      run: uv pip install pre-commit
      shell: bash
      env:
        UV_SYSTEM_PYTHON: 1

    - name: Cache pre-commit environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
          ~/.cache/R
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
