---
name: cleanup-terraform
description: Delete all AWS resources managed by a Terraform configuration.

inputs:
  role-to-assume:
    description: AWS IAM role to assume when running Terraform operations.
    required: true
  aws-account-id:
    description: AWS account ID to use to create resources.
    required: true
  working-directory:
    description: >
      Directory where the Terraform configuration to cleanup is stored.
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: ./actions/setup-terraform
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-account-id: ${{ inputs.aws-account-id }}
        working-directory: ${{ inputs.working-directory }}
        # These values can be anything, since Terraform doesn't need correct
        # values for variables in order to destroy resources
        batch-container-image-name: foo
        batch-job-definition-vcpu: bar
        batch-job-definition-memory: baz

    - name: Delete resources using Terraform
      run: terraform destroy -auto-approve
      working-directory: ${{ inputs.working-directory }}
      shell: bash
