---
name: cleanup-terraform

"on":
  workflow_call:
    secrets:
      AWS_IAM_ROLE_TO_ASSUME_ARN:
        required: true
      AWS_ACCOUNT_ID:
        required: true

env:
  TERRAFORM_WORKING_DIRECTORY: ./workflows/build-and-run-batch-job/terraform/

jobs:
  cleanup-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: ./actions/setup-terraform
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
          # These values can be anything, since Terraform doesn't need correct
          # values for variables in order to destroy resources
          batch-container-image-name: foo
          batch-job-definition-vcpu: bar
          batch-job-definition-memory: baz

      - name: Delete resources using Terraform
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        shell: bash
